// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Neptuo.Productivity.VisualStudio
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "8d017f34-e34e-4d2a-a9e9-124b463f8a87";
        public static Guid Package = new Guid(PackageString);
    }
}