// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Neptuo.Productivity.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "e7621347-77ce-4c11-82c9-b1ee7f946811";
        public static Guid Package = new Guid(PackageString);

        public const string CommandSetString = "4e34da48-c63d-46f0-9033-a21d21adfead";
        public static Guid CommandSet = new Guid(CommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FindInFolder = 0x0101;
    }
}