version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
before_build:
- ps: dotnet restore Neptuo.Productivity.sln
build:
  project: Neptuo.Productivity.sln
  verbosity: minimal
before_package:
- ps: .\tools\Vsix-SetVersion.ps1
artifacts:
- path: '*.vsix'