version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
before_build:
- ps: .\tools\AppVeyor-BeforeBuild.ps1
build:
  project: Neptuo.Productivity.sln
  verbosity: minimal
after_build:
- ps: .\tools\AppVeyor-PushArtifacts.ps1