version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
before_build:
- ps: >-
    dotnet restore Neptuo.Productivity.sln

    .\tools\Vsix-SetVersion.ps1
build:
  project: Neptuo.Productivity.sln
  verbosity: minimal
artifacts:
- path: '*.vsix'