// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Neptuo.Productivity.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "65b8ccaf-e638-4bdd-9508-3e153ffa115b";
        public const string CommandSetString = "ebd08d54-2fef-4985-ab8f-4a74bf64dc59";
        public static Guid Package = new Guid(PackageString);
        public static Guid CommandSet = new Guid(CommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddNewItem = 0x0101;
    }
}
