// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Neptuo.Productivity.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "6b896283-2b15-4f82-bb4e-186c94784f79";
        public static Guid Package = new Guid(PackageString);

        public const string CommandSetString = "e4a2c479-8fe3-4778-9dca-6a6f3ef5948c";
        public static Guid CommandSet = new Guid(CommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int DuplicateLineDown = 0x0101;
        public const int DuplicateLineUp = 0x0102;
    }
}